### ISSUE TITLE
How to create a pdf from single chapter

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafrocBook#24]
I am trying to create a pdf of a single chapter, specifically `83-classification-task.Rmd`, for sharing with others. 

I tried:
```
bookdown::render_book("83-classification-task.Rmd", output_format = "pdf_document", preview = T)
```

However, I get the following error:

```
Error producing PDF.
! LaTeX Error: File `epstopdf-base.sty' not found.
```

**Comment by dpc10ster** [comment]
This worked, sort of, ...
```
bookdown::render_book("83-classification-task.Rmd", output_format = bookdown::pdf_book(toc = FALSE), preview = TRUE)
```
Unfortunately it creates 67 pages of tables of contents of all preceding chapters in the book. The requested document is then fully rendered.

[RJafrocBook.pdf](https://github.com/dpc10ster/RJafrocBook/files/5459163/RJafrocBook.pdf)

**Comment by dpc10ster** [comment]
Also tried the following with same results:

```
bookdown::preview_chapter("83-classification-task.Rmd", output_format = bookdown::pdf_book(toc = FALSE))
```

**Comment by pwep** [comment]
Try this:

```
rmarkdown::render("83-classification-task.Rmd", bookdown::pdf_document2())
```

[`bookdown::pdf_document2`](https://bookdown.org/yihui/bookdown/a-single-document.html) needs to be used with `rmarkdown` (https://github.com/rstudio/bookdown/issues/255#issuecomment-264096568)

**Comment by dpc10ster** [comment]
Thanks!

**Comment by dpc10ster** [comment]
I just tried:

`rmarkdown::render("85-standalone-cad.Rmd", bookdown::pdf_document2())`

It failed with following message:

```
! LaTeX Error: Unknown float option `H'.

Error: LaTeX failed to compile 85-standalone-cad.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See 85-standalone-cad.log for more info.

```

Actually, that is not the whole story. The chapter compiled OK but with **numbers in Table 2 completely off**. I cleared the cache for the chapter, tried again, and got the above message. I get same error message after `Clean All`.

The book compiles OK with warning:

```
Output created: docs/RJafrocBook.pdf
Warning message:
In if (file.copy(list.files(from, full.names = TRUE), to, recursive = TRUE)) unlink(from,  :
  the condition has length > 1 and only the first element will be used

```

The contents look fine.

**Comment by pwep** [comment]
`! LaTeX Error: Unknown float option 'H'.` 

This error is due to the latex package `float` not being loaded. The YAML at the top of `85-standalone-cad.Rmd` has a [a line](https://github.com/dpc10ster/RJafrocBook/blob/4d3d70b45b4011c0b8e4e0ddb13f20ae32be3519/85-standalone-cad.Rmd#L6)  which should load the float package. However it is not appearing in the `85-standalone-cad.tex` output. I'm not even sure that the YAML is being actioned(!)

I deleted `85-standalone-cad.tex`, cleaned, checked for and loaded any updated R packages, and rebuilt 85, and it was OK.
My generated `85-standalone-cad.tex` file was slightly different, and contained the required call to the `float` package.

I'll keep looking to see if the problem re-appears.

**Comment by pwep** [comment]
I can see why the HTML table is struggling to get the colouring correct. It might be an idea to disable row colouring for that table (I'll find out how), or even colour the rows manually. Not sure on the missing columns in your output.

I've run

`Rscript -e 'rmarkdown::render("85-standalone-cad.Rmd", bookdown::pdf_document2(toc=TRUE))'`

to generate a stand-alone HTML output and it looks OK. It is also missing the row colouring.

Clearly the template being used for the whole book vs stand-alone is different. I'm trying to work out how to pass a YAML config file to the stand-alone build script, to control some of the rendering options (add point to the `.bib` files). I don't want to specify such details in the chapter itself as it could complicate the whole-book build.

**Comment by pwep** [comment]
> ```
> Output created: docs/RJafrocBook.pdf
> Warning message:
> In if (file.copy(list.files(from, full.names = TRUE), to, recursive = TRUE)) unlink(from,  :
>   the condition has length > 1 and only the first element will be used
> ```

I've starting seeing that too(!) Looks like it is something to do with the post-build tidy up. Possibly files are being removed before they can be copied. I'll reset the output folder and see what happens.

**Comment by dpc10ster** [comment]
It took me a while to figure out that this has to be run from the Terminal.
This is great. Now I can put single chapters on ResearchGate for comments.
Thanks, Dev
