### ISSUE TITLE
Aesthetics of document - figures, tables etc.

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafrocBook#25]
* The following text on pdf page 377 flows around the two tables.
> **The bottom line is that in all three cases the wAFROC yields the right conclusion, while the FROC comparison can only be made when the ... two performances are similar**
* The pdf generator keeps the two tables together (I don't have to have them together) but does not care what happens to the text.

<img width="433" alt="incorrect-text-flow" src="https://user-images.githubusercontent.com/33084612/98970786-56a62200-24de-11eb-8f48-9b8cc2671d44.png">

**Comment by pwep** [comment]
This will be a Latex rule I would think. I'll have a look at the generated `.tex` file and see what can be done.

**Comment by dpc10ster** [comment]
I think I figured it out; see YAML front matter in Chapter `13-froc-vs-afroc.Rmd`. The only problem is that the `html` output lists this front matter, which I don't want. 

```
output:
  rmarkdown::pdf_document:
    fig_caption: yes        
    includes:  
      in_header: R/learn/my_header.tex

```

The script `R/learn/my_header.tex` is in the R directory.

Have not implemented it in the chapter your are referring to, the subject of this `issue` post.

**Comment by dpc10ster** [comment]
The floating figures problem has been fixed. This is the current problem: the YAML appears in the output.

![example](https://user-images.githubusercontent.com/33084612/99708081-53c1a900-2a6b-11eb-9a24-c01ebbd5cf5f.png)

**Comment by pwep** [comment]
The YAML needs to be between `---` delimiters, and at the top of the document. At the moment it is contained in a fenced code block, and so won't be interpreted as YAML? Is it having the effect you want?

**Comment by dpc10ster** [comment]
**You just solved my problem!** I am keeping the issue open as I would like the table captions to be left justified (currently they are centered). The following solution, which I found from the web, does  not work:

```
---
header-includes:
   - \usepackage[justification=raggedright,labelfont=bf,singlelinecheck=false]{caption}
output:
  rmarkdown::pdf_document:
    fig_caption: yes        
    includes:  
      in_header: R/learn/my_header.tex
---
```

**Comment by pwep** [comment]
> I am keeping the issue open as I would like the table captions to be left justified

Just for the certain chapters or throughout the document?

**Comment by dpc10ster** [comment]
Ideally throughout the document!

**Comment by pwep** [comment]
In that case, the latex command could be added to the `preamble.tex` file. I'll try building now...

**Comment by pwep** [comment]
That looks like it might work...

<img width="549" alt="Screenshot 2020-11-19 at 20 18 11" src="https://user-images.githubusercontent.com/732331/99719554-5b517400-2aa4-11eb-9049-fe6ce4e6d1ac.png">

The space between the "Fig." and "21.1" in the main text below the caption is quite large. I guess Latex is interpreting the period after "Fig" as a full stop and spacing accordingly to get the required justification for a line. I'll have a look at that too.

**Comment by dpc10ster** [comment]
You are probably right. I don't mind replacing all my Fig. with Figures.
The table captions are OK in pdf ( left aligned) but not in html (centered)

Here is pdf:

![Table21 1](https://user-images.githubusercontent.com/33084612/99720880-655f7c80-2a7c-11eb-8f14-938bd1d84b73.png)

Here is html:

![21 2 3](https://user-images.githubusercontent.com/33084612/99720908-6d1f2100-2a7c-11eb-9eb6-6d91af7c274e.png)

**Comment by pwep** [comment]
There should be a global setting (probably an entry in a `.css` file) that will fix this, rather than have to specify alignment for each figure. I'll have a look now...

**Comment by pwep** [comment]
#26 should make the HTML table captions match the figure captions (light grey, left-aligned).

**Comment by dpc10ster** [comment]
I am leaving it open but renamed as "Aesthetics of document - figures, tables etc."

**Comment by dpc10ster** [comment]
On further thought, keeping this issue open does not make sense. Put it down to my inexperience with GitHub! Future such issues can be titled as 

>Aesthetics: blah blah
