### ISSUE TITLE
Website not building 

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafrocBook#33]
Error message visible under `Settings`:
> Your site is having problems building: The variable {{p_r} on line 46 in 19a-rsm-fitting.md was not properly closed with }}. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#tag-not-properly-terminated.

I noticed the website did not have the 3 quick-start chapters that I had just added. 

I changed 

`\frac{{p_r}^{n_r}}{n_r!}`

to

`\frac{p_r^{n_r}}{n_r!}`

And likewise for `q_r`. 

Did a successful git build and pushed repo https://github.com/dpc10ster/RJafrocBook/commit/b6ef386b4ba5eac2dc60bff15577b9585df18bc2.

**Comment by pwep** [comment]
Looks like GitHub Pages is trying to build the website using Jekyll. We probably need an empty `.nojekyll` file in the `gh_pages` branch (https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/). This will stop the pages being processed by Jekyll.

The `{{ ... }}`  is interpreted as a variable by Jekyll.

**Comment by dpc10ster** [comment]
Works. Thanks for the explanation.
