### ISSUE TITLE
GitHub Action failure

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafrocBook#35]
Commit https://github.com/dpc10ster/RJafrocBook/commit/e9e62d816abf69ba070adf3d85e2f8919cafc8a6

Failure in: 

`- uses: r-lib/actions/setup-r@v1`

> Failed to get R 4.0.3: Failed to get R 4.0.3: Failed to install gfortan: Error: The process '/usr/local/bin/brew' failed with exit code 1

Does not appear to be related to my code;

**Comment by pwep** [comment]
It looks to be a failure of the `brew` package manager on the Mac platform.It is trying to install `gfortan` - surely that should be `gfortran`. I expect that is an error in `r-lib/actions/setup-r@v1` which is called to install R. I'll take a look.

**Comment by pwep** [comment]
Ah, the mis-spelling is just in the error message. `brew` also known as _homebrew_ is the package manager for he Mac. There have been some recent changes to how it works. Other people are starting to see the issue too. Over on [r-lib/actions](https://github.com/r-lib/actions) an issue has just appeared, and also a pull request about this. Expect it to be addressed very shortly.

**Comment by dpc10ster** [comment]
I see they closed the issue, I will restart the build

**Comment by dpc10ster** [comment]
Works now
